Changed build scripts Avoid relying in xctool

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -6,51 +6,8 @@ export SCRIPT_DIR=$(dirname "$0")
 ## Configuration Variables
 ##
 
-SCHEMES="$@"
-
-config ()
-{
-    # The workspace to build.
-    #
-    # If not set and no workspace is found, the -workspace flag will not be passed
-    # to `xctool`.
-    #
-    # Only one of `XCWORKSPACE` and `XCODEPROJ` needs to be set. The former will
-    # take precedence.
-    : ${XCWORKSPACE=$(find_pattern "*.xcworkspace")}
-
-    # The project to build.
-    #
-    # If not set and no project is found, the -project flag will not be passed
-    # to `xctool`.
-    #
-    # Only one of `XCWORKSPACE` and `XCODEPROJ` needs to be set. The former will
-    # take precedence.
-    : ${XCODEPROJ=$(find_pattern "*.xcodeproj")}
-
-    # A bootstrap script to run before building.
-    #
-    # If this file does not exist, it is not considered an error.
-    : ${BOOTSTRAP="$SCRIPT_DIR/bootstrap"}
-
-    # Extra options to pass to xctool.
-    : ${XCTOOL_OPTIONS="RUN_CLANG_STATIC_ANALYZER=NO"}
-
-    # A whitespace-separated list of default schemes to build.
-    #
-    # Individual names can be quoted to avoid word splitting.
-    : ${SCHEMES:=$(xcodebuild -list -project "$XCODEPROJ" 2>/dev/null | awk -f "$SCRIPT_DIR/schemes.awk")}
-
-    # A whitespace-separated list of executables that must be present and locatable.
-    : ${REQUIRED_TOOLS="xctool"}
-
-    export XCWORKSPACE
-    export XCODEPROJ
-    export BOOTSTRAP
-    export XCTOOL_OPTIONS
-    export SCHEMES
-    export REQUIRED_TOOLS
-}
+# The name of the keychain to create for iOS code signing.
+KEYCHAIN=ios-build.keychain
 
 ##
 ## Build Process
@@ -58,116 +15,85 @@ config ()
 
 main ()
 {
-    config
-
-    if [ -n "$REQUIRED_TOOLS" ]
+    if [ -f Cartfile ]
     then
-        echo "*** Checking dependencies..."
-        check_deps
+      echo ""
+      echo "####### Importing Developer Certificates #######"
+      echo ""
+      import_certs
     fi
 
-    if [ -f "$BOOTSTRAP" ]
+    echo ""
+    echo "####### Bootstrap Phase #######"
+    echo ""
+    script/bootstrap
+    local status=$?
+
+    if [ $status -eq 0 ]
     then
-        echo "*** Bootstrapping..."
-        "$BOOTSTRAP" || exit $?
-    fi
-
-    echo "*** The following schemes will be built:"
-    echo "$SCHEMES" | xargs -n 1 echo "  "
-    echo
-
-    echo "$SCHEMES" | xargs -n 1 | (
-        local status=0
-
-        while read scheme
-        do
-            build_scheme "$scheme" || status=1
-        done
-
-        exit $status
-    )
-}
-
-check_deps ()
-{
-    for tool in $REQUIRED_TOOLS
-    do
-        which -s "$tool"
-        if [ "$?" -ne "0" ]
+      echo ""
+      echo ""
+      echo "####### Build & Test Phase #######"
+      echo ""
+      script/test | tee /tmp/build.test-output.txt
+      status=$?
+      if [ ! $status -eq 0 ]
+      then
+        log_file_path=`cat /tmp/build.test-output.txt | perl -l -ne '/(\/var\/folders.*\/com\.apple\.dt\.XCTest-status.*)\)/ && print $1'`
+        if [ ! -z "$log_file_path" ]
         then
-            echo "*** Error: $tool not found. Please install it and cibuild again."
-            exit 1
+          echo ""
+          echo " → The tests have failed. Printing output of log file '$log_file_path'."
+          cat $log_file_path
+          echo ""
         fi
-    done
-}
-
-find_pattern ()
-{
-    ls -d $1 2>/dev/null | head -n 1
-}
-
-run_xctool ()
-{
-    if [ -n "$XCWORKSPACE" ]
-    then
-        xctool -workspace "$XCWORKSPACE" $XCTOOL_OPTIONS "$@" 2>&1
-    elif [ -n "$XCODEPROJ" ]
-    then
-        xctool -project "$XCODEPROJ" $XCTOOL_OPTIONS "$@" 2>&1
-    else
-        echo "*** No workspace or project file found."
-        exit 1
-    fi
-}
-
-parse_build ()
-{
-    awk -f "$SCRIPT_DIR/xctool.awk" 2>&1 >/dev/null
-}
-
-build_scheme ()
-{
-    local scheme=$1
-
-    echo "*** Building and testing $scheme..."
-    echo
-
-    local sdkflag=
-    local action=test
-
-    # Determine whether we can run unit tests for this target.
-    run_xctool -scheme "$scheme" run-tests | parse_build
-
-    local awkstatus=$?
-
-    if [ "$awkstatus" -eq "1" ]
-    then
-        # SDK not found, try for iphonesimulator.
-        sdkflag="-sdk iphonesimulator"
-
-        # Determine whether the unit tests will run with iphonesimulator
-        run_xctool $sdkflag -scheme "$scheme" run-tests | parse_build
-
-        awkstatus=$?
-
-        if [ "$awkstatus" -ne "0" ]
-        then
-            # Unit tests will not run on iphonesimulator.
-            sdkflag=""
-        fi
+      fi
     fi
 
-    if [ "$awkstatus" -ne "0" ]
-    then
-        # Unit tests aren't supported.
-        action=build
-    fi
-
-    run_xctool $sdkflag -scheme "$scheme" $action
+    delete_keychain
+    exit $status
 }
 
-export -f build_scheme
-export -f run_xctool
-export -f parse_build
+import_certs ()
+{
+    # If this environment variable is missing, we must not be running on Travis.
+    if [ -z "$KEY_PASSWORD" ]
+    then
+        return 0
+    fi
+
+    echo " → Setting up code signing..."
+    local password=cibuild
+
+    # Create a temporary keychain for code signing.
+    security create-keychain -p "$password" "$KEYCHAIN"
+    security default-keychain -s "$KEYCHAIN"
+    security unlock-keychain -p "$password" "$KEYCHAIN"
+    security set-keychain-settings -t 3600 -l "$KEYCHAIN"
+
+    # Download the certificate for the Apple Worldwide Developer Relations
+    # Certificate Authority.
+    local certpath="$SCRIPT_DIR/apple_wwdr.cer"
+    curl -s 'https://developer.apple.com/certificationauthority/AppleWWDRCA.cer' > "$certpath"
+    security import "$certpath" -k "$KEYCHAIN" -T /usr/bin/codesign
+
+    # Import our development certificate.
+    security import "$SCRIPT_DIR/certificates/cibot.p12" -k "$KEYCHAIN" -P "$KEY_PASSWORD" -T /usr/bin/codesign
+}
+
+delete_keychain ()
+{
+    if [ -z "$KEY_PASSWORD" ]
+    then
+        return 0
+    fi
+
+    echo " → Removing temporary keychain"
+    security delete-keychain "$KEYCHAIN"
+    echo "    ✔ Temporary keychain successfully removed."
+}
+
+export -f import_certs
+export -f delete_keychain
 
 main
